# Generated by Django 5.2 on 2025-04-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaffeeKonfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis_pro_kg', models.DecimalField(decimal_places=2, help_text='Preis pro Kilogramm Bohnen in Euro', max_digits=6)),
                ('gramm_pro_tasse', models.DecimalField(decimal_places=2, help_text='Durchschnittlicher Verbrauch pro Tasse in Gramm', max_digits=5)),
                ('gueltig_ab', models.DateField(help_text='Gültig ab Datum')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Ist diese Konfiguration aktiv?')),
            ],
        ),
        migrations.CreateModel(
            name='Einlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('menge_gramm', models.PositiveIntegerField(help_text='Menge in Gramm')),
                ('wert_euro', models.DecimalField(decimal_places=2, help_text='Wert in Euro', max_digits=7)),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einlagen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Konsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('anzahl_tassen', models.PositiveIntegerField(default=1)),
                ('mahlvorgaenge', models.PositiveIntegerField(default=1, help_text='Wie oft wurde gemahlen?')),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutzerProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bevorzugte_mahlart', models.CharField(blank=True, max_length=100)),
                ('durchschnitt_tassen_pro_woche', models.PositiveIntegerField(default=0)),
                ('nutzer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
