# Generated by Django 5.2 on 2025-04-23 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaffee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbrechnungsWoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datum', models.DateField(help_text='Startdatum der Woche (Montag)')),
                ('end_datum', models.DateField(help_text='Enddatum der Woche (Sonntag)')),
                ('abgeschlossen', models.BooleanField(default=False, help_text='Wurde die Woche bereits abgerechnet?')),
            ],
            options={
                'verbose_name': 'Abrechnungswoche',
                'verbose_name_plural': 'Abrechnungswochen',
            },
        ),
        migrations.RemoveField(
            model_name='konsum',
            name='nutzer',
        ),
        migrations.AlterModelOptions(
            name='kaffeekonfiguration',
            options={'verbose_name': 'Kaffee-Konfiguration', 'verbose_name_plural': 'Kaffee-Konfigurationen'},
        ),
        migrations.AlterModelOptions(
            name='nutzerprofil',
            options={'verbose_name': 'Nutzerprofil', 'verbose_name_plural': 'Nutzerprofile'},
        ),
        migrations.AddField(
            model_name='nutzerprofil',
            name='kaffee_pro_tag',
            field=models.PositiveIntegerField(default=1, help_text='Tassen Kaffee pro Tag'),
        ),
        migrations.AddField(
            model_name='nutzerprofil',
            name='mahlvorgaenge_pro_kaffee',
            field=models.PositiveIntegerField(default=1, help_text='Wie oft wird pro Kaffee gemahlen?'),
        ),
        migrations.AddField(
            model_name='nutzerprofil',
            name='tage_pro_woche',
            field=models.PositiveIntegerField(default=0, help_text='Anzahl der Tage pro Woche im Büro'),
        ),
        migrations.CreateModel(
            name='KontoBewegung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('typ', models.CharField(choices=[('KAFFEE', 'Kaffeebohnen'), ('GELD', 'Geld'), ('SONSTIGES', 'Sonstiges/Zubehör'), ('KONSUM', 'Kaffeekonsum')], max_length=16)),
                ('menge_gramm', models.PositiveIntegerField(blank=True, help_text='Nur für Kaffeebohnen/Konsum', null=True)),
                ('wert_euro', models.DecimalField(blank=True, decimal_places=2, help_text='Nur für Geld/Sonstiges', max_digits=7, null=True)),
                ('beschreibung', models.CharField(blank=True, help_text='z.B. Milch, Entkalker, Zubehör, Kommentar', max_length=200)),
                ('mahlvorgaenge', models.PositiveIntegerField(blank=True, help_text='Nur für Konsum – wie oft gemahlen?', null=True)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontobewegungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konto-Bewegung',
                'verbose_name_plural': 'Konto-Bewegungen',
            },
        ),
        migrations.DeleteModel(
            name='Einlage',
        ),
        migrations.DeleteModel(
            name='Konsum',
        ),
    ]
