# Generated by Django 5.2 on 2025-04-23 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaffee', '0002_abrechnungswoche_remove_konsum_nutzer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontobewegung',
            name='saldo_wert',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wert, mit dem diese Bewegung den Kontostand beeinflusst (positiv/negativ)', max_digits=7),
        ),
    ]
