# Generated by Django 5.2 on 2025-04-25 10:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaffee', '0004_kontobewegung_ist_markiert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('KAFFEE', 'Kaffeebohnen-Einlage'), ('GELD', 'Geld-Einzahlung'), ('WOCHENVERBRAUCH', 'Wochenverbrauch'), ('AUSZAHLUNG', 'Auszahlung')], max_length=20)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('saldo_wert', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wert der Transaktion (positiv/negativ)', max_digits=7)),
                ('beschreibung', models.CharField(blank=True, max_length=200)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaktion',
                'verbose_name_plural': 'Transaktionen',
            },
        ),
        migrations.CreateModel(
            name='Auszahlung',
            fields=[
                ('transaktion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kaffee.transaktion')),
                ('bank_referenz', models.CharField(blank=True, help_text='z.B. IBAN oder Verwendungszweck', max_length=100)),
            ],
            bases=('kaffee.transaktion',),
        ),
        migrations.CreateModel(
            name='GeldEinzahlung',
            fields=[
                ('transaktion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kaffee.transaktion')),
                ('zahlungsreferenz', models.CharField(blank=True, help_text='z.B. PayPal-Transaktions-ID', max_length=100)),
            ],
            bases=('kaffee.transaktion',),
        ),
        migrations.CreateModel(
            name='KaffeeEinlage',
            fields=[
                ('transaktion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kaffee.transaktion')),
                ('menge_kg', models.DecimalField(decimal_places=2, help_text='Menge in kg', max_digits=6)),
                ('zusatz_info', models.TextField(blank=True, help_text="z.B. '5x 1kg vom Aldi'")),
            ],
            bases=('kaffee.transaktion',),
        ),
        migrations.CreateModel(
            name='Wochenverbrauch',
            fields=[
                ('transaktion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kaffee.transaktion')),
                ('start_datum', models.DateField()),
                ('end_datum', models.DateField()),
            ],
            bases=('kaffee.transaktion',),
        ),
        migrations.DeleteModel(
            name='KontoBewegung',
        ),
    ]
